name: Deploy Services on VMware

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Connect to VMware VM and Deploy Services
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "Fetching service paths from PostgreSQL..."
            
            SERVICES=$(sudo -u postgres psql -d mydatabase -t -c "SELECT name, file_path FROM ServiceTemplate;")

            echo "Found services: $SERVICES"
            
            while IFS='|' read -r SERVICE_NAME FILE_PATH; do
              FILE_PATH=$(echo $FILE_PATH | xargs)
              echo "Deploying $SERVICE_NAME from $FILE_PATH ..."

              if [[ -f "$FILE_PATH/scripts/deploy.sh" ]]; then
                echo "Executing $FILE_PATH/scripts/deploy.sh"
                bash "$FILE_PATH/scripts/deploy.sh"
              else
                echo "No deploy script found for $SERVICE_NAME"
              fi
            done <<< "$SERVICES"
          EOF

