name: Deploy Nginx on External K8s Server (Local with SSH)

on:
  workflow_dispatch:  # 수동 실행 가능하도록 설정

jobs:
  deploy:
    runs-on: self-hosted  # GitHub Actions 실행 서버 (192.168.179.134)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Nginx Deployment Info from Local PostgreSQL via SSH
        run: |
          echo "Fetching Nginx deployment information from PostgreSQL via SSH (192.168.179.134)..."
          
          # 같은 서버지만 SSH를 통해 PostgreSQL 정보 조회
          SERVICE_INFO=$(ssh -o StrictHostKeyChecking=no root@192.168.179.134 \
            "sudo -u postgres psql -d solmakasedb -t -c \"SELECT name, deploy_script FROM servicetemplate WHERE name = 'nginx-web';\"")

          echo "Found Nginx service info:"
          echo "$SERVICE_INFO"

          SERVICE_NAME=$(echo "$SERVICE_INFO" | awk -F '|' '{print $1}' | xargs)
          DEPLOY_SCRIPT=$(echo "$SERVICE_INFO" | awk -F '|' '{print $2}' | xargs)

          echo "----------------------------------------"
          echo "Service: $SERVICE_NAME"
          echo "Deploy Script Path: $DEPLOY_SCRIPT"

          # YAML 파일 경로 정의
          YAML_FILE="/var/lib/pgsql/16/data/service_templates/nginx-web/yaml/deployment.yaml"

          echo "Copying deployment script and YAML to Kubernetes master (192.168.179.134) via SSH..."
          ssh -o StrictHostKeyChecking=no root@192.168.179.134 "cp $DEPLOY_SCRIPT /tmp/deploy.sh && cp $YAML_FILE /tmp/deployment.yaml"

      - name: Execute Deploy Script on Local Kubernetes Master via SSH
        run: |
          echo "Executing deployment script on Kubernetes master via SSH (192.168.179.134)..."
          ssh -o StrictHostKeyChecking=no root@192.168.179.134 "chmod +x /tmp/deploy.sh && /tmp/deploy.sh"
