name: Test Fetch & Deploy Nginx on Remote K8s Master

on:
  workflow_dispatch:

jobs:
  deploy-nginx:
    runs-on: self-hosted  # GitHub Actions 서버 (192.168.179.100)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Nginx Deployment Info from Remote PostgreSQL (192.168.179.101)
        run: |
          echo "Fetching Nginx deployment information from PostgreSQL (192.168.179.101)..."
          
          SERVICE_INFO=$(ssh -o StrictHostKeyChecking=no root@192.168.179.101 \
            "sudo -u postgres psql -d mydatabase -t -c \"SELECT name, deploy_script FROM ServiceTemplate WHERE name = 'nginx-web';\"")

          echo "Found Nginx service info:"
          echo "$SERVICE_INFO"

          SERVICE_NAME=$(echo "$SERVICE_INFO" | awk -F '|' '{print $1}' | xargs)
          DEPLOY_SCRIPT=$(echo "$SERVICE_INFO" | awk -F '|' '{print $2}' | xargs)

          echo "----------------------------------------"
          echo "Service: $SERVICE_NAME"
          echo "Deploy Script Path: $DEPLOY_SCRIPT"

          # YAML 파일 경로 정의
          YAML_FILE="/var/lib/pgsql/16/data/service_templates/nginx-web/yaml/deployment.yaml"

          echo "Copying deployment script and YAML to Kubernetes master (192.168.179.134)..."
          scp -o StrictHostKeyChecking=no root@192.168.179.101:$DEPLOY_SCRIPT root@192.168.179.134:/tmp/deploy.sh
          scp -o StrictHostKeyChecking=no root@192.168.179.101:$YAML_FILE root@192.168.179.134:/tmp/deployment.yaml

      - name: Execute Deploy Script on Kubernetes Master (192.168.179.134)
        run: |
          echo "Executing deployment script on Kubernetes master (192.168.179.134)..."
          ssh -o StrictHostKeyChecking=no root@192.168.179.134 "chmod +x /tmp/deploy.sh && /tmp/deploy.sh"
